### ISSUE TITLE
App.test.js fails two tests

### ISSUE THREAD

**Issue by harcod** [livgust/macovidvaccines.com#142]
● Console

    console.error
      Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
          at AlertBanner (/home/rob/source/macovid/livgust/macovidvaccines.com/src/components/AlertBanner.js:51:21)
          at div
          at Grid (/home/rob/source/macovid/livgust/macovidvaccines.com/node_modules/@material-ui/core/Grid/Grid.js:241:35)
          at WithStyles(ForwardRef(Grid)) (/home/rob/source/macovid/livgust/macovidvaccines.com/node_modules/@material-ui/styles/withStyles/withStyles.js:67:31)
          at div
          at Grid (/home/rob/source/macovid/livgust/macovidvaccines.com/node_modules/@material-ui/core/Grid/Grid.js:241:35)
          at WithStyles(ForwardRef(Grid)) (/home/rob/source/macovid/livgust/macovidvaccines.com/node_modules/@material-ui/styles/withStyles/withStyles.js:67:31)
          at div
          at Grid (/home/rob/source/macovid/livgust/macovidvaccines.com/node_modules/@material-ui/core/Grid/Grid.js:241:35)
          at WithStyles(ForwardRef(Grid)) (/home/rob/source/macovid/livgust/macovidvaccines.com/node_modules/@material-ui/styles/withStyles/withStyles.js:67:31)
          at main
          at MainComponent (/home/rob/source/macovid/livgust/macovidvaccines.com/src/App.js:75:21)
          at ThemeProvider (/home/rob/source/macovid/livgust/macovidvaccines.com/node_modules/@material-ui/styles/ThemeProvider/ThemeProvider.js:48:24)
          at App

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at warnForMissingKey (node_modules/react-dom/cjs/react-dom.development.js:13135:5)
      at warnOnInvalidKey (node_modules/react-dom/cjs/react-dom.development.js:13602:11)
      at reconcileChildrenArray (node_modules/react-dom/cjs/react-dom.development.js:13651:21)
      at reconcileChildFibers (node_modules/react-dom/cjs/react-dom.development.js:14125:14)
      at reconcileChildren (node_modules/react-dom/cjs/react-dom.development.js:16990:28)
      at mountIndeterminateComponent (node_modules/react-dom/cjs/react-dom.development.js:17890:5)

    console.error
      Warning: Each child in a list should have a unique "key" prop.
      
      Check the render method of `StateEligibility`. See https://reactjs.org/link/warning-keys for more information.
          at CriterionItem (/home/rob/source/macovid/livgust/macovidvaccines.com/src/components/StateEligibility.js:188:26)
          at StateEligibility (/home/rob/source/macovid/livgust/macovidvaccines.com/src/components/StateEligibility.js:120:21)
          at div
          at Grid (/home/rob/source/macovid/livgust/macovidvaccines.com/node_modules/@material-ui/core/Grid/Grid.js:241:35)
          at WithStyles(ForwardRef(Grid)) (/home/rob/source/macovid/livgust/macovidvaccines.com/node_modules/@material-ui/styles/withStyles/withStyles.js:67:31)
          at div
          at Grid (/home/rob/source/macovid/livgust/macovidvaccines.com/node_modules/@material-ui/core/Grid/Grid.js:241:35)
          at WithStyles(ForwardRef(Grid)) (/home/rob/source/macovid/livgust/macovidvaccines.com/node_modules/@material-ui/styles/withStyles/withStyles.js:67:31)
          at div
          at Grid (/home/rob/source/macovid/livgust/macovidvaccines.com/node_modules/@material-ui/core/Grid/Grid.js:241:35)
          at WithStyles(ForwardRef(Grid)) (/home/rob/source/macovid/livgust/macovidvaccines.com/node_modules/@material-ui/styles/withStyles/withStyles.js:67:31)
          at main
          at MainComponent (/home/rob/source/macovid/livgust/macovidvaccines.com/src/App.js:75:21)
          at ThemeProvider (/home/rob/source/macovid/livgust/macovidvaccines.com/node_modules/@material-ui/styles/ThemeProvider/ThemeProvider.js:48:24)
          at App

      148 |                                 // However the interaction with fragments is unclear, so ensure
      149 |                                 // title fragments and listitems are unique, as they are siblings.
    > 150 |                                 <React.Fragment key={"title" + index}>
          |                                 ^
      151 |                                     {group.title ? (
      152 |                                         // We don't display a title for the first
      153 |                                         // group, for some reason...

      at printWarning (node_modules/react/cjs/react-jsx-dev-runtime.development.js:117:30)
      at error (node_modules/react/cjs/react-jsx-dev-runtime.development.js:93:5)
      at validateExplicitKey (node_modules/react/cjs/react-jsx-dev-runtime.development.js:986:5)
      at validateChildKeys (node_modules/react/cjs/react-jsx-dev-runtime.development.js:1013:11)
      at jsxWithValidation (node_modules/react/cjs/react-jsx-dev-runtime.development.js:1174:15)
      at map (src/components/StateEligibility.js:150:33)
          at Array.map (<anonymous>)
      at StateEligibility (src/components/StateEligibility.js:144:41)

**Comment by harcod** [comment]
Also... had to skip a test regarding "role=alert". I think this has to do with having multiple items with role = alert at the same time.

Line 80-85, App.test.js
```
        test.skip("it displays an error message", async function () {
            await act(async function () {
                render(<App />);
            });

            expect(screen.getByRole("alert")).toBeInTheDocument();
        });

```

**Comment by harcod** [comment]
Three is another skipped test because of recent changes to filtering. It is marked as TODO
