### ISSUE TITLE
Nested <p> react errors

### ISSUE THREAD

**Issue by johnhawkinson** [livgust/macovidvaccines.com#51]
Clicking on a restriction box (e.g. "Greenfield Senior Center") when running in dev mode produces a complaint about nested `<p>` tags. It appears to be in part because CovidAppointmentTable.js passes text with `<p>` in it to HelpDialog.js, which then wraps everything in `<p>` tag. However, removing HelpDialog's wrapper does not correct the error.

Traceback:

```
index.js:1 Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.
    at p
    at p
    at p
    at Typography (http://localhost:3000/static/js/0.chunk.js:32532:28)
    at WithStyles(ForwardRef(Typography)) (http://localhost:3000/static/js/0.chunk.js:48644:31)
    at DialogContentText
    at WithStyles(ForwardRef(DialogContentText)) (http://localhost:3000/static/js/0.chunk.js:48644:31)
    at div
    at DialogContent (http://localhost:3000/static/js/0.chunk.js:8687:23)
    at WithStyles(ForwardRef(DialogContent)) (http://localhost:3000/static/js/0.chunk.js:48644:31)
    at div
    at Paper (http://localhost:3000/static/js/0.chunk.js:20504:23)
    at WithStyles(ForwardRef(Paper)) (http://localhost:3000/static/js/0.chunk.js:48644:31)
    at div
    at Transition (http://localhost:3000/static/js/0.chunk.js:120574:30)
    at Fade (http://localhost:3000/static/js/0.chunk.js:10539:24)
    at Unstable_TrapFocus (http://localhost:3000/static/js/0.chunk.js:32683:24)
    at div
    at Portal (http://localhost:3000/static/js/0.chunk.js:21590:24)
    at Modal (http://localhost:3000/static/js/0.chunk.js:18742:83)
    at Dialog (http://localhost:3000/static/js/0.chunk.js:8254:29)
    at WithStyles(ForwardRef(Dialog)) (http://localhost:3000/static/js/0.chunk.js:48644:31)
    at HelpDialog (http://localhost:3000/static/js/main.chunk.js:950:3)
    at RestrictionNotifier (http://localhost:3000/static/js/main.chunk.js:486:3)
    at span
    at Typography (http://localhost:3000/static/js/0.chunk.js:32532:28)
    at WithStyles(ForwardRef(Typography)) (http://localhost:3000/static/js/0.chunk.js:48644:31)
    at div
    at div
    at CardHeader (http://localhost:3000/static/js/0.chunk.js:5804:22)
    at WithStyles(ForwardRef(CardHeader)) (http://localhost:3000/static/js/0.chunk.js:48644:31)
    at div
    at Paper (http://localhost:3000/static/js/0.chunk.js:20504:23)
    at WithStyles(ForwardRef(Paper)) (http://localhost:3000/static/js/0.chunk.js:48644:31)
    at Card (http://localhost:3000/static/js/0.chunk.js:5360:23)
    at WithStyles(ForwardRef(Card)) (http://localhost:3000/static/js/0.chunk.js:48644:31)
    at div
    at LocationCard (http://localhost:3000/static/js/main.chunk.js:583:3)
    at div
    at section
    at CovidAppointmentTable (http://localhost:3000/static/js/main.chunk.js:379:19)
    at div
    at Grid (http://localhost:3000/static/js/0.chunk.js:12459:35)
    at WithStyles(ForwardRef(Grid)) (http://localhost:3000/static/js/0.chunk.js:48644:31)
    at div
    at Grid (http://localhost:3000/static/js/0.chunk.js:12459:35)
    at WithStyles(ForwardRef(Grid)) (http://localhost:3000/static/js/0.chunk.js:48644:31)
    at main
    at ThemeProvider (http://localhost:3000/static/js/0.chunk.js:47346:24)
    at App (http://localhost:3000/static/js/main.chunk.js:75:19)
```

I'm filing this as requested by Liv at this morning's standup, but I am not sure it is worth much effort.

**Comment by markogrady1** [comment]
removing the `<p>` wrapper from HelpDialog.js does fix the above error

**Comment by johnhawkinson** [comment]
Weird. Not for me.
Note that you only get the warning the first time you click the button.

Trying again, though, as you can see, it goes from 3 `at p` lines to two:

```
index.js:1 Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.
    at p
    at p
    at Typography (http://localhost:3000/static/js/0.chunk.js:32532:28)
    at WithStyles(ForwardRef(Typography)) (http://localhost:3000/static/js/0.chunk.js:40062:31)
    at DialogContentText
    at WithStyles(ForwardRef(DialogContentText)) (http://localhost:3000/static/js/0.chunk.js:40062:31)
    at div
    at DialogContent (http://localhost:3000/static/js/0.chunk.js:8687:23)
    at WithStyles(ForwardRef(DialogContent)) (http://localhost:3000/static/js/0.chunk.js:40062:31)
    at div
    at Paper (http://localhost:3000/static/js/0.chunk.js:20504:23)
    at WithStyles(ForwardRef(Paper)) (http://localhost:3000/static/js/0.chunk.js:40062:31)
    at div
    at Transition (http://localhost:3000/static/js/0.chunk.js:111992:30)
    at Fade (http://localhost:3000/static/js/0.chunk.js:10539:24)
    at Unstable_TrapFocus (http://localhost:3000/static/js/0.chunk.js:32683:24)
    at div
    at Portal (http://localhost:3000/static/js/0.chunk.js:21590:24)
    at Modal (http://localhost:3000/static/js/0.chunk.js:18742:83)
    at Dialog (http://localhost:3000/static/js/0.chunk.js:8254:29)
    at WithStyles(ForwardRef(Dialog)) (http://localhost:3000/static/js/0.chunk.js:40062:31)
    at HelpDialog (http://localhost:3000/static/js/main.chunk.js:962:3)
    at RestrictionNotifier (http://localhost:3000/static/js/main.chunk.js:490:3)
    at span
    at Typography (http://localhost:3000/static/js/0.chunk.js:32532:28)
    at WithStyles(ForwardRef(Typography)) (http://localhost:3000/static/js/0.chunk.js:40062:31)
    at div
    at div
    at CardHeader (http://localhost:3000/static/js/0.chunk.js:5804:22)
    at WithStyles(ForwardRef(CardHeader)) (http://localhost:3000/static/js/0.chunk.js:40062:31)
    at div
    at Paper (http://localhost:3000/static/js/0.chunk.js:20504:23)
    at WithStyles(ForwardRef(Paper)) (http://localhost:3000/static/js/0.chunk.js:40062:31)
    at Card (http://localhost:3000/static/js/0.chunk.js:5360:23)
    at WithStyles(ForwardRef(Card)) (http://localhost:3000/static/js/0.chunk.js:40062:31)
    at div
    at LocationCard (http://localhost:3000/static/js/main.chunk.js:581:3)
    at div
    at section
    at CovidAppointmentTable (http://localhost:3000/static/js/main.chunk.js:383:19)
    at div
    at Grid (http://localhost:3000/static/js/0.chunk.js:12459:35)
    at WithStyles(ForwardRef(Grid)) (http://localhost:3000/static/js/0.chunk.js:40062:31)
    at div
    at Grid (http://localhost:3000/static/js/0.chunk.js:12459:35)
    at WithStyles(ForwardRef(Grid)) (http://localhost:3000/static/js/0.chunk.js:40062:31)
    at main
    at ThemeProvider (http://localhost:3000/static/js/0.chunk.js:38764:24)
    at App (http://localhost:3000/static/js/main.chunk.js:88:19)
```

Not clear to me where the next one up the chain is coming from.

And, of course, I'd imagine that removing these `<p>`s might have visual effect that is undesired (but maybe not).

**Comment by aceyoung9** [comment]
This is happening because the `<DialogContentText>` component renders a `<p>` by default. I've made a PR that fixes this. (#70 )
